<a href="https://colab.research.google.com/github/Visheshshahu-06/Basics_on_python/blob/main/Vishesh_basic_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
For *list its {append, insert, remove, sort}
*String {upper, lover, replace, split}
*Dictionaries {get, keys, values, items}
*Tuples {index, count, len}
'''

'\nFor *list its {append, insert, remove, sort}\n*String {upper, lover, replace, split}\n*Dictionaries {get, keys, values, items}\n*Tuples {index, count, len}\n'

In [2]:
#QUETION 01
def reverse_and_concatenate(A, B):
    reversed_A = A[::-1]
    result = reversed_A + B
    return result

string_A = "Hello"
string_B = "World"
result = reverse_and_concatenate(string_A, string_B)
print(result)

olleHWorld


In [3]:
#Que 02
def find_highest_working_female(work_hours, hourly_rate=20):
    max_hours = 0
    female_worker = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_worker = name

    if female_worker:
        pay = max_hours * hourly_rate
        return f"The female worker who worked the most hours is {female_worker} with {max_hours} hours. She should be paid ${pay}."
    else:
        return "No female workers found."

work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'), ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]

result = find_highest_working_female(work_hours)
print(result)

The female worker who worked the most hours is Penny with 920 hours. She should be paid $18400.


In [4]:
#Quetion 03 A
import numpy as np

base_matrix = np.array([[1, 1], [2, 2]])

matrix = np.tile(base_matrix, (2, 2))

print(matrix)

[[1 1 1 1]
 [2 2 2 2]
 [1 1 1 1]
 [2 2 2 2]]


In [5]:
#B
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

if matrix1.shape[1] == matrix2.shape[0]:
    dot_product = np.dot(matrix1, matrix2)
    print("Dot Product Result:")
    print(dot_product)
else:
    print("Matrix dimensions are not compatible for dot product.")

Dot Product Result:
[[19 22]
 [43 50]]


In [6]:
#Quetion 03 A
import numpy as np

sub_matrix = np.array([[1, 1], [2, 2]])

result_matrix = np.tile(sub_matrix, (3, 3))

print(result_matrix)

[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]
